<?php
// /admin/sales_report.php
require_once '../includes/auth.php';
require_once '../config/database.php';
checkAccess(['admin', 'manager']);

$cid = $_SESSION['company_id'];

// Auto-patch check for live server
try {
    $pdo->exec("ALTER TABLE dsr ADD COLUMN IF NOT EXISTS product_id INT NULL DEFAULT NULL AFTER user_id");
    $pdo->exec("ALTER TABLE dsr ADD COLUMN IF NOT EXISTS sold_price DECIMAL(15,2) NULL DEFAULT NULL AFTER deal_status");
} catch (Exception $e) {
    try { $pdo->exec("ALTER TABLE dsr ADD COLUMN product_id INT NULL DEFAULT NULL AFTER user_id"); } catch(Exception $ex){}
    try { $pdo->exec("ALTER TABLE dsr ADD COLUMN sold_price DECIMAL(15,2) NULL DEFAULT NULL AFTER deal_status"); } catch(Exception $ex){}
}
$branch_ids = getAccessibleBranchIds($pdo, $cid);
$cids_in = implode(',', $branch_ids);

// 1. Fetch Sales Data (Closed Won deals)
$stmt = $pdo->prepare("
    SELECT 
        d.*, 
        u.name as staff_name, 
        p.name as product_name, 
        c.name as branch_name 
    FROM dsr d
    JOIN users u ON d.user_id = u.id
    LEFT JOIN products p ON d.product_id = p.id
    LEFT JOIN companies c ON d.company_id = c.id
    WHERE d.company_id IN ($cids_in) 
    AND d.deal_status = 'Closed Won'
    ORDER BY d.visit_date DESC, d.created_at DESC
");
$stmt->execute();
$sales = $stmt->fetchAll();

// 2. Stats
$total_revenue = 0;
foreach ($sales as $s) {
    $total_revenue += (float)($s['sold_price'] ?? 0);
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Closed Deals & Sales Report - DRHrms</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../assets/css/style.css?v=1774440084">
    <link rel="stylesheet" href="../assets/css/admin.css?v=1774440084">
    <style>
        .sales-stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1.5rem; margin-bottom: 2rem; }
        .stat-card { background: #fff; padding: 1.5rem; border-radius: 12px; border: 1px solid var(--glass-border); box-shadow: var(--shadow-sm); }
        .stat-val { font-size: 1.8rem; font-weight: 800; color: #10b981; margin-top: 5px; }
        .product-badge { background: #eef2ff; color: #6366f1; padding: 4px 10px; border-radius: 20px; font-size: 0.75rem; font-weight: 600; }
    </style>
</head>
<body>
<?php include 'includes/sidebar.php'; ?>
<div class="main-wrapper" style="flex: 1; margin-left: 260px;">
    <?php include 'includes/topbar.php'; ?>
    <main class="main-content" style="margin-left: 0; width: 100%; padding: 2rem 3rem;">
        
        <div class="page-header">
            <div>
                <h1>Closed Deals & Sales Report</h1>
                <p style="color:var(--text-muted)">Comprehensive list of products sold and revenue generated by your team.</p>
            </div>
            <button onclick="window.print()" class="btn btn-outline">Print Report</button>
        </div>

        <div class="sales-stats">
            <div class="stat-card">
                <span style="color:var(--text-muted); font-size:0.85rem; font-weight:600; text-transform:uppercase;">Total Revenue</span>
                <div class="stat-val">₹<?= number_format($total_revenue, 2) ?></div>
            </div>
            <div class="stat-card">
                <span style="color:var(--text-muted); font-size:0.85rem; font-weight:600; text-transform:uppercase;">Closed Deals</span>
                <div class="stat-val" style="color:var(--primary-color)"><?= count($sales) ?></div>
            </div>
        </div>

        <div class="content-card">
            <div class="card-header">
                <h3>Transaction Record</h3>
            </div>
            <div style="overflow-x:auto;">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Client Name</th>
                            <th>Product Sold</th>
                            <th>Sold Price</th>
                            <th>Sales Person</th>
                            <th>Branch</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($sales as $s): ?>
                        <tr>
                            <td><?= date('d M, Y', strtotime($s['visit_date'])) ?></td>
                            <td><strong><?= htmlspecialchars($s['client_name']) ?></strong></td>
                            <td>
                                <?php if ($s['product_name']): ?>
                                    <span class="product-badge"><?= htmlspecialchars($s['product_name']) ?></span>
                                <?php else: ?>
                                    <span style="color:var(--text-muted); font-style:italic;">Untracked Product</span>
                                <?php endif; ?>
                            </td>
                            <td style="font-weight:700; color:#10b981;">₹<?= number_format($s['sold_price'], 2) ?></td>
                            <td><?= htmlspecialchars($s['staff_name']) ?></td>
                            <td><span style="font-size:0.85rem; color:var(--text-muted);"><?= htmlspecialchars($s['branch_name'] ?? 'Main') ?></span></td>
                        </tr>
                        <?php endforeach; ?>
                        <?php if (empty($sales)): ?>
                        <tr>
                            <td colspan="6" style="text-align:center; padding:3rem; color:var(--text-muted);">
                                No closed deals found. When a DSR is submitted with "Closed Won" status, it will appear here.
                            </td>
                        </tr>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>

    </main>
</div>
</body>
</html>
